# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "oidc-webhook-authenticator.name" . }}-resource-reader-binding
  labels:
    app.kubernetes.io/name: {{ include "oidc-webhook-authenticator.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "oidc-webhook-authenticator.name" . }}-resource-reader
subjects:
{{- if and .Values.virtualGarden.enabled .Values.virtualGarden.user.name  }}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.virtualGarden.user.name  }}
{{- else }}
- kind: ServiceAccount
  name: {{ include "oidc-webhook-authenticator.name" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
