# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "oidc-webhook-authenticator.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "oidc-webhook-authenticator.name" . }}
rules:
- apiGroups:
  - authentication.gardener.cloud
  resources:
  - openidconnects
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "oidc-webhook-authenticator.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "oidc-webhook-authenticator.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "oidc-webhook-authenticator.name" . }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ include "oidc-webhook-authenticator.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "oidc-webhook-authenticator.name" . }}
  namespace: kube-system
  labels:
    app.kubernetes.io/name: {{ include "oidc-webhook-authenticator.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ include "oidc-webhook-authenticator.name" . }}
