# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "oidc-webhook-authenticator.name" . }}
  {{- if .Values.global.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "oidc-webhook-authenticator.name" . }}
  {{- end }}
webhooks:
- name: validation.oidc.webhook.authenticator
  rules:
  - apiGroups:
    - "authentication.gardener.cloud"
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openidconnects
  failurePolicy: Fail
  objectSelector: {}
  namespaceSelector: {}
  sideEffects: None
  admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    {{- if .Values.virtualGarden.enabled }}
    url: {{ printf "https://%s.%s/webhooks/validating" (include "oidc-webhook-authenticator.name" .) (.Release.Namespace) }}
    {{- else }}
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "oidc-webhook-authenticator.name" . }}
      path: /webhooks/validating
    {{- end }}
    {{- if and .Values.virtualGarden.enabled .Values.global.certManager.enabled}}
    {{- fail "When .virtualGarden.enabled is true global.certManager.enabled should be false" }}
    {{- else if ( not .Values.global.certManager.enabled ) }}
    caBundle: {{ required ".Values.webhookConfig.caBundle is required" .Values.webhookConfig.caBundle |  b64enc }}
    {{- end }}
