# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

virtualGarden:
  enabled: false

replicaCount: 1

image:
  repository: eu.gcr.io/gardener-project/gardener/oidc-webhook-authenticator
  tag: v0.1.0
  pullPolicy: IfNotPresent

webhookConfig:
  tls:
      crt: |
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        ...
        -----END RSA PRIVATE KEY-----

# Kubeconfig to the target cluster. In-cluster configuration will be used if not specified.
# If serviceAccountTokenVolumeProjection.enabled is set to `true` then this value is required.
kubeconfig: 

authKubeconfig: 

resources:
  requests:
   cpu: 100m
   memory: 64Mi
  limits:
   cpu: 200m
   memory: 256Mi

serviceAccountTokenVolumeProjection:
  enabled: false
  expirationSeconds: 1800
  audience: ""
