apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    insecure-skip-tls-verify: true
    server: https://control-plane.minikube.internal:10443/validate-token # the kube-apiserver cannot use cluster-dns
users:
- name: token
  user:
    client-certificate: /var/lib/minikube/certs/apiserver.crt
    client-key: /var/lib/minikube/certs/apiserver.key
current-context: webhook
contexts:
- context:
    cluster: local
    user: token
  name: webhook
