# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.global.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "oidc-webhook-authenticator.name" . }}-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "oidc-webhook-authenticator.name" . }}
spec:
  ca:
    secretName: {{ include "oidc-webhook-authenticator.name" . }}-ca
{{- end }}
