# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{- if or ( not .Values.automountServiceAccountToken ) .Values.auth.kubeconfig }}
apiVersion: v1
kind: Secret
metadata:
  name: oidc-webhook-authenticator-auth-kubeconfig
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: {{ include "oidc-webhook-authenticator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  kubeconfig: {{ required ".Values.auth.kubeconfig is required" .Values.auth.kubeconfig | b64enc }}
{{- end }}
