# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{- if ( not .Values.global.certManager.enabled ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oidc-webhook-authenticator.name" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "oidc-webhook-authenticator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  tls.crt: {{ required ".Values.webhookConfig.tls.crt is required" .Values.webhookConfig.tls.crt | b64enc }}
  tls.key: {{ required ".Values.webhookConfig.tls.key is required" .Values.webhookConfig.tls.key | b64enc }}
{{- end }}
